name: better_player
description: Advanced video player based on video_player and Chewie. It's solves many typical use cases and it's easy to run.
version: 0.0.9
homepage: https://github.com/Stash-Ventures/betterplayer
documentation: https://jhomlala.github.io/betterplayer/

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.2.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  # wakelock: 
  #   git: https://github.com/ShadyBoshra2012/wakelock/tree/main/wakelock
  meta: ^1.7.0
  flutter_widget_from_html_core: ^0.10.1
  visibility_detector: ^0.4.0+2
  path_provider: ^2.0.10
  collection: ^1.16.0
  xml: ^6.1.0
  wakelock_plus: ^1.1.1

dev_dependencies:
  lint: ^2.1.2
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.jhomlala.better_player
        pluginClass: BetterPlayerPlugin
      ios:
        pluginClass: BetterPlayerPlugin